### PR TITLE
Update Readme.md for commented require()s

### PR DESCRIPTION
**Pull request by johntron**

### CODE REVIEW

**Comment by matthewmueller** [comment]
i think it'd be nice to handle this actually. i guess it might be difficult with block comments though

**Comment by jonathanong** [comment]
this is already handled, no? https://github.com/visionmedia/node-requires/blob/master/test/index.js#L29

**Comment by matthewmueller** [comment]
yep, looks like it just got added yesterday.

**Comment by jonathanong** [comment]
oh shoot didn't realized it got published yesterday haha

**Pull request closed without merging**
