### PR TITLE
Space padded

### PR DESCRIPTION
**Pull request by anton-ryzhov**
Match

``` JS
require(  'spaced'  );
require( 
  'indented'
);
```

Some codestyles uses this forms.

### CODE REVIEW

**Comment by timaschew** [comment]
it fixes #7 

@visionmedia maybe you can move this repo to @node-modules or @webdeps
@jonathanong you have too many orgs, haha. which one would fit better?

**Comment by popomore** [comment]
+1 transfer to @node-modules

**Comment by tj** [comment]
woah who writes requires like that haha

**Comment by anton-ryzhov** [comment]
Thanks for merge, but it still doesn't work for me because of #8.
`component` does replace `require( 'foo' )`, but in comments, **not in** code. Take a look #8 please, it is not only about dirty comments.

**Pull request merged**
